### ISSUE TITLE
Web interface for cluster management

### ISSUE THREAD

**Issue by jjmrocha** [0blivi0n/oblivion#6]
- Add node do cluster
- Remove node from cluster

**Comment by goncalo-pereira** [comment]
Web interface mockup
![cluster_home](https://cloud.githubusercontent.com/assets/3442235/6151460/b576c7f2-b20d-11e4-8f76-c16050cfda1d.png)

**Comment by goncalo-pereira** [comment]
Moved to https://github.com/0blivi0n/oblivion-admin/issues/
