### ISSUE TITLE
Web interface for cache management

### ISSUE THREAD

**Issue by jjmrocha** [0blivi0n/oblivion#7]
- List of caches
- Create cache
- Delete cache
- Flush cache
- Cache size
- Cache configuration

**Comment by goncalo-pereira** [comment]
Web interface mockup
![cache_home](https://cloud.githubusercontent.com/assets/3442235/6151481/e91d891a-b20d-11e4-9619-a58657cadf8b.png)

**Comment by goncalo-pereira** [comment]
Moved to https://github.com/0blivi0n/oblivion-admin/issues/
